### ISSUE TITLE
t/test2_tools_http_ua_mojo__httpbin.t failures (bogus hostname is not bogus enough)

### ISSUE THREAD

**Issue by eserte** [plicease/Test2-Tools-HTTP-UA-Mojo#5]
On some of my systems the test suite fails like this: http://www.cpantesters.org/cpan/report/e135c1d2-d7b6-11ec-b6ed-3e7c1f24ea8f

The problem seems to be the same as described in https://github.com/tokuhirom/Furl/issues/128

The usual fix: add a dot to the bogus hostname. This seems to work:
```
diff --git a/t/test2_tools_http_ua_mojo__httpbin.t b/t/test2_tools_http_ua_mojo__httpbin.t
index fd48055..a444d1e 100644
--- a/t/test2_tools_http_ua_mojo__httpbin.t
+++ b/t/test2_tools_http_ua_mojo__httpbin.t
@@ -95,7 +95,7 @@ is(
 is(
   intercept {
     $ret = http_request(
-      GET('http://bogus.httpbin.org/status/200'),
+      GET('http://bogus.httpbin.org./status/200'),
     );
   },
   array {
```

**Comment by plicease** [comment]
Thank you for reporting this.  I have applied your suggested fix and released as 0.05 on its way to CPAN now.
